name: iOS Tests

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'mobile/iOS'
    paths:
      - 'mobile/iOS/**'
      - 'rust_core/**'
      - '.github/workflows/ios-tests.yml'

jobs:
  test:
    name: Run iOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust_core/target
          key: ${{ runner.os }}-cargo-ios-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-lipo
        run: cargo install cargo-lipo

      - name: Build Rust Core for iOS
        working-directory: rust_core
        run: |
          cargo lipo --release --targets aarch64-apple-ios-sim
          mkdir -p ../mobile/iOS/CyrillicIME/libs
          cp target/universal/release/libcyrillic_ime_core.a ../mobile/iOS/CyrillicIME/libs/

      - name: Run iOS tests
        working-directory: mobile/iOS
        run: |
          xcodebuild test \
            -scheme CyrillicIME \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -only-testing:CyrillicIMETests \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ios-test-results
          path: mobile/iOS/build/test-results/
